// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockSupabase } from './mock-client';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

const isBrowser = typeof window !== "undefined" && typeof localStorage !== "undefined";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabase: any;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || !isBrowser) {
  console.warn("[OFFLINE MODE] Using mock Supabase client for local testing");
  supabase = mockSupabase;
} else {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export { supabase };